# -*- coding: utf-8 -*-
# Exports "The answer" tab's underlying data + logic + full lineage to Excel.
# Source: app_data2.json (exact dataset baked into live index.html as `const D`).
import json
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

d = json.load(open('app_data2.json', encoding='utf-8'))
months = d['months']
mlabels = [m.replace('�', chr(0xB7)) for m in d['mlabels']]  # fix mis-decoded middle-dot
classes = d['classes']
KEYS = ['kwh', 'energy', 'fuel', 'ipp', 'demand', 'cust_chg', 'rev']
KLABEL = {'kwh': 'Volume (kWh)', 'energy': 'Energy', 'fuel': 'Fuel', 'ipp': 'IPP',
          'demand': 'Demand (kVA)', 'cust_chg': 'Customer charge', 'rev': 'Total revenue'}

# JMD/US$ billing FX rate per month -- hardcoded in the live page (app2_template.html), NOT
# generated by any of the analysis/*.py scripts. Sourced manually from BOJ/billing rate each
# month; 2026-06 is flagged estimated (no confirmed rate at build time, carried fwd from May).
FX = {'2025-05': 159.4628, '2025-10': 161.2235, '2025-11': 161.4640, '2025-12': 161.2044,
      '2026-01': 159.7395, '2026-02': 157.5400, '2026-03': 157.2639, '2026-04': 158.5846,
      '2026-05': 158.16, '2026-06': 158.16}
FX_EST = {'2026-06': 1}

wb = Workbook()

HEAD = Font(bold=True, color='FFFFFF')
HEAD_FILL = PatternFill('solid', fgColor='1F4E5F')
SUB_FILL = PatternFill('solid', fgColor='DCE6F1')
thin = Side(style='thin', color='B7C4D0')
BORDER = Border(left=thin, right=thin, top=thin, bottom=thin)

def style_header(ws, row, ncols, start_col=1):
    for c in range(start_col, start_col + ncols):
        cell = ws.cell(row=row, column=c)
        cell.font = HEAD
        cell.fill = HEAD_FILL
        cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
        cell.border = BORDER

# ── 1. Logic / read-me sheet ────────────────────────────────────────────
ws = wb.active
ws.title = 'Logic'
ws.column_dimensions['A'].width = 110
lines = [
("THE ANSWER — HOW THE CHART IS BUILT", True, 14),
("", False, 11),
("What it shows", True, 12),
("A bar chart of % change, period A -> period B, for 6 revenue components: Volume (kWh), Energy, Fuel, IPP, "
 "Demand (kVA), Customer charge. Plus 3 KPI tiles: Volume % change, Revenue % change (vs volume), Demand % change.", False, 11),
("", False, 11),
("Formula (exact JS, deck_tabs.js)", True, 12),
("  pctV(a,b) = (b/a - 1) * 100", False, 11),
("  comp = [ ['Volume (kWh)', pctV(T.kwh[A],T.kwh[B])],", False, 11),
("           ['Energy',       pctV(T.energy[A],T.energy[B])],", False, 11),
("           ['Fuel',         pctV(T.fuel[A],T.fuel[B])],", False, 11),
("           ['IPP',          pctV(T.ipp[A],T.ipp[B])],", False, 11),
("           ['Demand (kVA)', pctV(T.demand[A],T.demand[B])],", False, 11),
("           ['Customer',     pctV(T.cust_chg[A],T.cust_chg[B])] ]", False, 11),
("  where T = D.total (see 'Total_by_Month' tab) and A/B = the two months picked in the 'Compare' dropdowns.", False, 11),
("  Default A = first month in the dataset, default B = last month, but the user can pick ANY two of the 10 months.", False, 11),
("", False, 11),
("Try it yourself", True, 12),
("  Use the 'Answer_Compare' tab — pick Period A and Period B from the dropdowns, it recomputes the same 6 numbers "
 "with live Excel formulas pointing at 'Total_by_Month'.", False, 11),
("", False, 11),
("The narrative logic (why this tab exists)", True, 12),
("  Energy and Fuel scale roughly with kWh (variable, volume-driven). Demand charge is billed on peak kVA and does NOT "
 "scale with kWh growth automatically. So when volume (kWh) grows faster than contracted/billed demand, the blended "
 "J$/kWh realization dilutes -- revenue grows slower than volume. The chart is designed to make you compare the "
 "Volume bar to the Demand bar: if Volume > Demand, that's the dilution story.", False, 11),
("  Clicking any bar drills into the top-5 / bottom-5 CUSTOMER ACCOUNTS driving that component's change "
 "(renderAnswerContributors() in deck_tabs.js) -- see 'Accounts' tab for the same account-level numbers.", False, 11),
("", False, 11),
("WHERE THE NUMBERS COME FROM (full lineage)", True, 14),
("", False, 11),
("1. RAW SOURCE — JPS billing system export, one file per month:", True, 11),
("     'Billing Details Report <Month> <Year>.xlsx' (or raw CIS tab-delimited export), meter/account grain,", False, 11),
("     columns incl. Cust_Code, Srat_Code, rate_class, Parish, net_kwh_billed_consump, net_revenue,", False, 11),
("     KVAP/KVAL/KVAO demand, KWHP/KWHL/KWHO energy, fuel (+ off/partial/on-peak), IPP_Charge, Cust_Charge.", False, 11),
("     Location: C:\\Users\\jwilson\\Downloads\\ (one workbook dropped per month as billing closes).", False, 11),
("", False, 11),
("2. analysis/corrected_scan.py", True, 11),
("     Reads each month's raw file. Maps every row to a rate CLASS (RT10/20/40/50/60/70/Other) via", False, 11),
("     'Rate categorry Data mapping.csv' (rate_class first, Srat_Code fallback), and to a PARISH GROUP via", False, 11),
("     'Parish Grouping.csv'. RT10/RT20 (mass market) are bucketed by kWh consumption band; RT40+ (large", False, 11),
("     accounts) are kept at individual customer x rate-class grain. Writes -> corrected.json (raw aggregates,", False, 11),
("     one month appended at a time, idempotent re-run).", False, 11),
("", False, 11),
("3. analysis/gen_appdata3.py", True, 11),
("     Reads corrected.json. Sums each class's kwh/rev/demand(=KVAP+KVAL+KVAO)/fuel/energy/ipp/cust_chg", False, 11),
("     across ALL classes into D.total (the 'Total_by_Month' tab). Also emits D.cls (per-class) and D.accts", False, 11),
("     (per-account, RT40+ only -- non RT10/RT20). Writes -> app_data2.json. THIS FILE is the direct source", False, 11),
("     for every number in this workbook.", False, 11),
("", False, 11),
("4. analysis/build_full.py", True, 11),
("     Bakes app_data2.json's JSON verbatim into app2_template.html + deck_tabs.js (the chart/tab code) as a", False, 11),
("     single JS literal:  const D = { ...app_data2.json contents... };  Writes -> index.html. This is a BUILD-TIME", False, 11),
("     snapshot -- the live site does not re-query anything for these numbers. To refresh, re-run steps 1-4 with", False, 11),
("     that month's new billing file, then redeploy index.html (vercel --prod).", False, 11),
("", False, 11),
("5. Live site: salesanalysis.jmfinancelab.com (Vercel, D:\\Projects\\Sales_Platform\\salesanalysis_deploy)", True, 11),
("     deck_tabs.js reads D.total/D.cls/D.accts directly from that embedded object for every tab: The answer,", False, 11),
("     YoY bridge, Big customers, With/without, Movers, Top var movers.", False, 11),
("", False, 11),
("YOY BRIDGE — HOW IT'S BUILT (separate tab, separate logic from 'The answer')", True, 14),
("", False, 11),
("What it shows", True, 12),
("  A revenue bridge in US$M from a Start period to an End period: Start -> +/-Energy -> +/-Fuel -> +/-IPP -> "
 "+/-Demand -> +/-Customer -> +/-Other/adj -> +/-FX -> End. Bar chart shows the same deltas ranked by size; the "
 "waterfall chart shows them as a running total that reconciles exactly Start + all deltas = End.", False, 11),
("", False, 11),
("Three comparison modes (button group on the tab)", True, 12),
("  Month : Start/End = exactly the two months picked in the Compare dropdowns.", False, 11),
("  YTD   : Start/End = Jan-through-(month of A) of A's year vs Jan-through-(month of B) of B's year -- e.g. "
 "picking Mar'26 in YTD mode sums Jan+Feb+Mar'26. Flagged '(partial)' if fewer months exist than the calendar "
 "would call for (e.g. only 1 of the year's months is loaded).", False, 11),
("  Full Year : Start/End = every loaded month in A's / B's calendar year (Jan-Dec cap). Flagged '(Nmo, partial)' "
 "if the dataset doesn't yet have all 12 months of that year.", False, 11),
("", False, 11),
("Step-by-step formula (exact JS, renderBridge() in deck_tabs.js)", True, 12),
("  1. Sum each J$ component (Energy, Fuel, IPP, Demand, Customer, Total revenue) over ALL months in the Start "
 "set -> jA.*, and over all months in the End set -> jB.* (raw J$, then /1e6 for J$M).", False, 11),
("  2. fxA = average JMD/US$ billing rate over the Start set's months. fxB = same for the End set.", False, 11),
("  3. Component deltas, converted to US$ at the constant STARTING rate (fxA) -- this isolates the pure JMD-driven "
 "change with currency held fixed:", False, 11),
("       Energy_delta  = (jB.energy  - jA.energy)  / fxA", False, 11),
("       Fuel_delta    = (jB.fuel    - jA.fuel)    / fxA", False, 11),
("       IPP_delta     = (jB.ipp     - jA.ipp)     / fxA", False, 11),
("       Demand_delta  = (jB.demand  - jA.demand)  / fxA", False, 11),
("       Customer_delta= (jB.cust_chg- jA.cust_chg)/ fxA", False, 11),
("  4. Start (US$) = jA.rev / fxA        End (US$) = jB.rev / fxB        Net change = End - Start", False, 11),
("  5. Other/adj = the leftover JMD revenue change (at fxA) not explained by the 5 components above -- rounding, "
 "revenue_adj / net_billing_adj line items that don't get their own bar. = (jB.rev-jA.rev)/fxA - sum(5 deltas).", False, 11),
("  6. FX effect = whatever is STILL left after Other/adj -- i.e. the pure currency-devaluation impact:", False, 11),
("       FX = Net_change - sum(5 component deltas) - Other/adj", False, 11),
("     This guarantees, by construction: Start + Energy + Fuel + IPP + Demand + Customer + Other/adj + FX = End, "
 "exactly, every time -- the waterfall always reconciles.", False, 11),
("", False, 11),
("KPI tiles on the tab", True, 12),
("  Net revenue  = Net_change ($), % = pctV(Start,End), sub-label shows volume(kWh) % change over the same sets.", False, 11),
("  FX effect    = the FX line above, sub-label shows fxA -> fxB.", False, 11),
("  IPP (pass-through) = IPP_delta, labelled margin-neutral (JPS doesn't earn margin on IPP cost pass-through).", False, 11),
("", False, 11),
("Where the FX rates come from -- IMPORTANT GAP", True, 12),
("  D.fx (JMD/US$ per month) is HARD-CODED directly in app2_template.html/index.html -- it is the one number in "
 "this entire app NOT produced by any analysis/*.py script. It must be updated by hand each month from the BOJ/"
 "billing rate. 2026-06 is flagged fxEst=1 (estimated/carried-forward -- no confirmed rate at last build). See "
 "'Month_Index' tab for the exact table and 'YoY_Bridge' tab to recompute the bridge for any period pair/mode.", False, 11),
("", False, 11),
("EXCEPTION -- one live query, NOT part of the above:", True, 11),
("     The 'View account detail' modal (meter-level table you get after clicking a customer) calls Supabase table", False, 11),
("     jps_actuals live via anon key + RPC get_acct_detail, scoped by exact account name/year/month. That is the", False, 11),
("     only part of this app that is NOT a build-time snapshot -- everything on 'The answer' tab and the other 5", False, 11),
("     analysis tabs comes from the static embedded dataset described above.", False, 11),
]
r = 1
for text, bold, size in lines:
    c = ws.cell(row=r, column=1, value=text)
    c.font = Font(bold=bold, size=size, color='1F4E5F' if bold and size >= 13 else ('333333' if not bold else '1F4E5F'))
    c.alignment = Alignment(wrap_text=True, vertical='top')
    r += 1
ws.freeze_panes = 'A2'

# ── 2. Total_by_Month — exact D.total ───────────────────────────────────
ws2 = wb.create_sheet('Total_by_Month')
ws2.cell(row=1, column=1, value='Metric (D.total.*)')
for j, ml in enumerate(mlabels):
    ws2.cell(row=1, column=2 + j, value=ml)
style_header(ws2, 1, len(mlabels) + 1)
ws2.column_dimensions['A'].width = 20
for i, k in enumerate(KEYS):
    row = 2 + i
    ws2.cell(row=row, column=1, value=KLABEL[k]).font = Font(bold=True)
    ws2.cell(row=row, column=1).fill = SUB_FILL
    for j, mo in enumerate(months):
        val = d['total'][k][j]
        cell = ws2.cell(row=row, column=2 + j, value=round(val, 1))
        cell.number_format = '#,##0.0'
        cell.border = BORDER
ws2.freeze_panes = 'B2'
for j in range(len(mlabels)):
    ws2.column_dimensions[get_column_letter(2 + j)].width = 14

# ── 3. Answer_Compare — pick 2 periods, recompute the chart's 6 numbers ─
ws3 = wb.create_sheet('Answer_Compare')
ws3['A1'] = 'Period A'
ws3['A1'].font = Font(bold=True)
ws3['B1'] = mlabels[0]
ws3['A2'] = 'Period B'
ws3['A2'].font = Font(bold=True)
ws3['B2'] = mlabels[-1]
dv = DataValidation(type='list', formula1='"' + ','.join(mlabels) + '"', allow_blank=False)
ws3.add_data_validation(dv)
dv.add(ws3['B1'])
dv.add(ws3['B2'])
ws3['D1'] = "Pick Period A/B above -- matches Total_by_Month's header row exactly (=HLOOKUP)."
ws3['D1'].font = Font(italic=True, color='777777')

ws3.cell(row=4, column=1, value='Component').font = Font(bold=True)
ws3.cell(row=4, column=2, value='Value @ A').font = Font(bold=True)
ws3.cell(row=4, column=3, value='Value @ B').font = Font(bold=True)
ws3.cell(row=4, column=4, value='% change  (=(B/A-1)*100)').font = Font(bold=True)
style_header(ws3, 4, 4)
for i, k in enumerate(KEYS):
    r = 5 + i
    ws3.cell(row=r, column=1, value=KLABEL[k])
    colA = f"HLOOKUP($B$1,Total_by_Month!$B$1:$K$8,{2+i},FALSE)"
    colB = f"HLOOKUP($B$2,Total_by_Month!$B$1:$K$8,{2+i},FALSE)"
    ws3.cell(row=r, column=2, value=f"={colA}").number_format = '#,##0.0'
    ws3.cell(row=r, column=3, value=f"={colB}").number_format = '#,##0.0'
    ws3.cell(row=r, column=4, value=f"=(C{r}/B{r}-1)*100").number_format = '+0.0%;-0.0%'
    ws3.cell(row=r, column=4).value = f"=(C{r}/B{r}-1)*100"
ws3.column_dimensions['A'].width = 18
for col in ['B', 'C', 'D']:
    ws3.column_dimensions[col].width = 16
note = ("Chart bars = the 6 rows above (Volume, Energy, Fuel, IPP, Demand, Customer). "
        "KPI tiles on the live tab: Volume % chg, Revenue % chg (row 'Total revenue' not shown as a bar but "
        "used for the KPI), Demand % chg vs Volume % chg.")
ws3['A13'] = note
ws3['A13'].alignment = Alignment(wrap_text=True)
ws3.merge_cells('A13:D15')

# ── 3b. Month_Index — per-month raw components + FX rate (feeds YoY_Bridge) ─
wsM = wb.create_sheet('Month_Index')
mhdrs = ['MonthKey', 'Label', 'Year', 'MonthNum', 'Idx', 'FX rate', 'FX Est?'] + [KLABEL[k] + ' (raw)' for k in KEYS]
for c, h in enumerate(mhdrs, start=1):
    wsM.cell(row=1, column=c, value=h)
style_header(wsM, 1, len(mhdrs))
for j, mo in enumerate(months):
    r = 2 + j
    yr, mn = int(mo[:4]), int(mo[5:7])
    wsM.cell(row=r, column=1, value=mo)
    wsM.cell(row=r, column=2, value=mlabels[j])
    wsM.cell(row=r, column=3, value=yr)
    wsM.cell(row=r, column=4, value=mn)
    wsM.cell(row=r, column=5, value=j + 1)
    wsM.cell(row=r, column=6, value=FX.get(mo)).number_format = '0.0000'
    wsM.cell(row=r, column=7, value=1 if FX_EST.get(mo) else 0)
    for i, k in enumerate(KEYS):
        wsM.cell(row=r, column=8 + i, value=round(d['total'][k][j], 1)).number_format = '#,##0.0'
nM = len(months)
lastRow = 1 + nM
# Selection lookups (cols T/U — kept clear of Q/R, which hold the InSetA/InSetB data columns below)
wsM['T1'] = 'YearA'; wsM['U1'] = f"=INDEX(C2:C{lastRow},MATCH(YoY_Bridge!$B$1,$B$2:$B${lastRow},0))"
wsM['T2'] = 'MonthNumA'; wsM['U2'] = f"=INDEX(D2:D{lastRow},MATCH(YoY_Bridge!$B$1,$B$2:$B${lastRow},0))"
wsM['T3'] = 'YearB'; wsM['U3'] = f"=INDEX(C2:C{lastRow},MATCH(YoY_Bridge!$B$2,$B$2:$B${lastRow},0))"
wsM['T4'] = 'MonthNumB'; wsM['U4'] = f"=INDEX(D2:D{lastRow},MATCH(YoY_Bridge!$B$2,$B$2:$B${lastRow},0))"
wsM.cell(row=1, column=17).value = 'InSetA'
wsM.cell(row=1, column=18).value = 'InSetB'
wsM.cell(row=1, column=17).font = Font(bold=True)
wsM.cell(row=1, column=18).font = Font(bold=True)
for j in range(nM):
    r = 2 + j
    inA = (f"=IF(YoY_Bridge!$B$3=\"Month\",$B{r}=YoY_Bridge!$B$1,"
           f"IF(YoY_Bridge!$B$3=\"YTD\",AND($C{r}=$U$1,$D{r}<=$U$2),$C{r}=$U$1))*1")
    inB = (f"=IF(YoY_Bridge!$B$3=\"Month\",$B{r}=YoY_Bridge!$B$2,"
           f"IF(YoY_Bridge!$B$3=\"YTD\",AND($C{r}=$U$3,$D{r}<=$U$4),$C{r}=$U$3))*1")
    wsM.cell(row=r, column=17, value=inA)
    wsM.cell(row=r, column=18, value=inB)
wsM.column_dimensions['A'].width = 11
wsM.column_dimensions['B'].width = 10
for col in ['C', 'D', 'E', 'F', 'G']:
    wsM.column_dimensions[col].width = 10
for i in range(len(KEYS)):
    wsM.column_dimensions[get_column_letter(8 + i)].width = 15
wsM.freeze_panes = 'C2'

# ── 3c. YoY_Bridge — replicate renderBridge() with live formulas ───────
wsB = wb.create_sheet('YoY_Bridge')
wsB['A1'] = 'Period A (Start)'; wsB['A1'].font = Font(bold=True)
wsB['B1'] = mlabels[0]
wsB['A2'] = 'Period B (End)'; wsB['A2'].font = Font(bold=True)
wsB['B2'] = mlabels[-1]
wsB['A3'] = 'Mode'; wsB['A3'].font = Font(bold=True)
wsB['B3'] = 'Month'
dvM = DataValidation(type='list', formula1='"' + ','.join(mlabels) + '"', allow_blank=False)
wsB.add_data_validation(dvM); dvM.add(wsB['B1']); dvM.add(wsB['B2'])
dvMode = DataValidation(type='list', formula1='"Month,YTD,FY"', allow_blank=False)
wsB.add_data_validation(dvMode); dvMode.add(wsB['B3'])
wsB['D1'] = "Mode: Month = exactly these 2 months. YTD = Jan..month(X) of X's year. FY = full loaded year of X."
wsB['D1'].font = Font(italic=True, color='777777')
wsB['D1'].alignment = Alignment(wrap_text=True)
wsB.merge_cells('D1:H2')

M = 'Month_Index'
# column letters in Month_Index for kwh,energy,fuel,ipp,demand,cust_chg,rev = H..N
COLMAP = dict(zip(KEYS, ['H', 'I', 'J', 'K', 'L', 'M', 'N']))

ws_r = 5
labels_hdr = ['Metric', 'Sum @ A (J$M)', 'Sum @ B (J$M)']
for c, h in enumerate(labels_hdr, start=1):
    wsB.cell(row=ws_r, column=c, value=h).font = Font(bold=True)
style_header(wsB, ws_r, 3)
jrows = {}
for i, k in enumerate(['energy', 'fuel', 'ipp', 'demand', 'cust_chg', 'rev', 'kwh']):
    r = ws_r + 1 + i
    col = COLMAP[k]
    wsB.cell(row=r, column=1, value=KLABEL[k])
    wsB.cell(row=r, column=2, value=f"=SUMPRODUCT({M}!$Q$2:$Q${lastRow},{M}!${col}$2:${col}${lastRow})/1000000").number_format = '#,##0.0'
    wsB.cell(row=r, column=3, value=f"=SUMPRODUCT({M}!$R$2:$R${lastRow},{M}!${col}$2:${col}${lastRow})/1000000").number_format = '#,##0.0'
    jrows[k] = r

fxRow = ws_r + 9
wsB.cell(row=fxRow, column=1, value='Avg FX @ A (fxA)').font = Font(bold=True)
wsB.cell(row=fxRow, column=2, value=f"=SUMPRODUCT({M}!$Q$2:$Q${lastRow},{M}!$F$2:$F${lastRow})/SUM({M}!$Q$2:$Q${lastRow})").number_format = '0.0000'
wsB.cell(row=fxRow + 1, column=1, value='Avg FX @ B (fxB)').font = Font(bold=True)
wsB.cell(row=fxRow + 1, column=2, value=f"=SUMPRODUCT({M}!$R$2:$R${lastRow},{M}!$F$2:$F${lastRow})/SUM({M}!$R$2:$R${lastRow})").number_format = '0.0000'
wsB.cell(row=fxRow + 2, column=1, value='FX estimated in set?').font = Font(bold=True)
wsB.cell(row=fxRow + 2, column=2, value=(f"=IF(OR(SUMPRODUCT({M}!$Q$2:$Q${lastRow},{M}!$G$2:$G${lastRow})>0,"
                                          f"SUMPRODUCT({M}!$R$2:$R${lastRow},{M}!$G$2:$G${lastRow})>0),\"YES ⚠\",\"no\")"))
fxA_ref, fxB_ref = f"$B${fxRow}", f"$B${fxRow+1}"

bridgeHdrRow = fxRow + 4
wsB.cell(row=bridgeHdrRow, column=1, value='Bridge step').font = Font(bold=True)
wsB.cell(row=bridgeHdrRow, column=2, value='US$M').font = Font(bold=True)
style_header(wsB, bridgeHdrRow, 2)
br = bridgeHdrRow + 1
wsB.cell(row=br, column=1, value='Start (Period A, US$)')
wsB.cell(row=br, column=2, value=f"=B{jrows['rev']}/{fxA_ref}").number_format = '$#,##0.0'
startRowRef = f"B{br}"
deltas = {}
for i, k in enumerate(['energy', 'fuel', 'ipp', 'demand', 'cust_chg']):
    r = br + 1 + i
    wsB.cell(row=r, column=1, value=KLABEL[k])
    wsB.cell(row=r, column=2, value=f"=(C{jrows[k]}-B{jrows[k]})/{fxA_ref}").number_format = '+$#,##0.0;-$#,##0.0'
    deltas[k] = f"B{r}"
compSumFormula = "+".join(deltas.values())
otherRow = br + 6
wsB.cell(row=otherRow, column=1, value='Other/adj (unexplained JMD, at fxA)')
wsB.cell(row=otherRow, column=2, value=f"=(C{jrows['rev']}-B{jrows['rev']})/{fxA_ref}-({compSumFormula})").number_format = '+$#,##0.0;-$#,##0.0'
fxRowOut = br + 7
wsB.cell(row=fxRowOut, column=1, value='FX effect')
netRef = f"(C{jrows['rev']}/{fxB_ref}-B{jrows['rev']}/{fxA_ref})"
wsB.cell(row=fxRowOut, column=2, value=f"={netRef}-({compSumFormula})-B{otherRow}").number_format = '+$#,##0.0;-$#,##0.0'
endRow = br + 8
wsB.cell(row=endRow, column=1, value='End (Period B, US$)')
wsB.cell(row=endRow, column=2, value=f"=C{jrows['rev']}/{fxB_ref}").number_format = '$#,##0.0'
checkRow = br + 10
wsB.cell(row=checkRow, column=1, value='Check: Start+deltas+Other+FX-End (should = 0)').font = Font(italic=True)
wsB.cell(row=checkRow, column=2, value=f"=B{br}+({compSumFormula})+B{otherRow}+B{fxRowOut}-B{endRow}").number_format = '0.0000'
wsB.column_dimensions['A'].width = 34
wsB.column_dimensions['B'].width = 16
wsB.column_dimensions['C'].width = 16

# ── 4. By_Class — D.cls, tidy long table ────────────────────────────────
ws4 = wb.create_sheet('By_Class')
hdrs = ['Class', 'Metric'] + mlabels
for c, h in enumerate(hdrs, start=1):
    ws4.cell(row=1, column=c, value=h)
style_header(ws4, 1, len(hdrs))
ws4.column_dimensions['A'].width = 10
ws4.column_dimensions['B'].width = 18
r = 2
for cls in classes:
    for k in KEYS:
        ws4.cell(row=r, column=1, value=cls)
        ws4.cell(row=r, column=2, value=KLABEL[k])
        for j, mo in enumerate(months):
            val = d['cls'][cls][k][j]
            cell = ws4.cell(row=r, column=3 + j, value=round(val, 1))
            cell.number_format = '#,##0.0'
        r += 1
ws4.freeze_panes = 'C2'
for j in range(len(mlabels)):
    ws4.column_dimensions[get_column_letter(3 + j)].width = 13

# ── 5. Accounts — D.accts, wide (RT40+ only, matches app's account grain)
ws5 = wb.create_sheet('Accounts')
metrics = ['kwh', 'rev', 'dem', 'energy', 'fuel', 'ipp', 'cust']
mlabel_short = [m.split('�')[0] if '�' in m else m for m in d['mlabels']]
hdrs = ['Account ID', 'Name', 'Class', 'Parish group']
for met in metrics:
    for ml in mlabels:
        hdrs.append(f'{met}_{ml}')
for c, h in enumerate(hdrs, start=1):
    ws5.cell(row=1, column=c, value=h)
style_header(ws5, 1, len(hdrs))
ws5.column_dimensions['A'].width = 12
ws5.column_dimensions['B'].width = 30
ws5.column_dimensions['C'].width = 8
ws5.column_dimensions['D'].width = 14
accts_sorted = sorted(d['accts'], key=lambda a: -(a['rev'][-1] if a['rev'] else 0))
for i, a in enumerate(accts_sorted):
    r = 2 + i
    ws5.cell(row=r, column=1, value=a['id'])
    ws5.cell(row=r, column=2, value=a['n'])
    ws5.cell(row=r, column=3, value=a['c'])
    ws5.cell(row=r, column=4, value=a.get('pg', ''))
    col = 5
    for met in metrics:
        arr = a.get(met, [0] * len(months))
        for j in range(len(months)):
            v = arr[j] if j < len(arr) else 0
            cell = ws5.cell(row=r, column=col, value=round(v, 1) if v else 0)
            cell.number_format = '#,##0'
            col += 1
ws5.freeze_panes = 'E2'
ws5.auto_filter.ref = f"A1:{get_column_letter(len(hdrs))}{1+len(accts_sorted)}"

# ── 6. Source_Trace — file lineage table ────────────────────────────────
ws6 = wb.create_sheet('Source_Trace')
rows = [
 ('Step', 'File / Location', 'What it does'),
 ('1. Raw billing export', r'C:\Users\jwilson\Downloads\Billing Details Report <Month>.xlsx (per month)',
  'JPS CIS billing system export, meter/account grain: kWh, revenue, demand (KVAP/KVAL/KVAO), energy, fuel, IPP, customer charge, rate_class, parish.'),
 ('2. Mapping tables', r'C:\Users\jwilson\Downloads\Rate categorry Data mapping.csv, Parish Grouping.csv',
  'rate_class/Srat_Code -> rate CLASS (RT10..RT70/Other); Parish -> Parish Group.'),
 ('3. Aggregation script', r'D:\Projects\Sales_Platform\analysis\corrected_scan.py',
  'Reads raw file(s) + mapping, aggregates to (Srat_Code, rate_class) x Parish and (customer x rate_class) for RT40+. Writes corrected.json.'),
 ('4. Intermediate data', r'D:\Projects\Sales_Platform\analysis\corrected.json',
  'Cumulative store, one month appended per run. Grain: srat/class/parish totals + per-account (RT40+) monthly components.'),
 ('5. App-data build', r'D:\Projects\Sales_Platform\analysis\gen_appdata3.py',
  "Sums corrected.json into D.total (all classes), D.cls (per class), D.accts (per RT40+ account). Writes app_data2.json -- this workbook's numbers = that file, verbatim."),
 ('6. Page build', r'D:\Projects\Sales_Platform\analysis\build_full.py + app2_template.html + deck_tabs.js',
  "Splices deck_tabs.js (chart/tab logic) into the template, bakes app_data2.json in as literal `const D = {...}`, writes index.html. Build-time snapshot -- no runtime query for these numbers."),
 ('7. Deploy', r'D:\Projects\Sales_Platform\salesanalysis_deploy\index.html -> Vercel', 'Live at salesanalysis.jmfinancelab.com.'),
 ('8. EXCEPTION -- live query', 'Supabase jps_actuals table (RPC get_acct_detail), anon key',
  'Only used by the "View account detail" drill-down modal for a live meter-level table on the exact account/month clicked. Everything else on every tab is the static build-time dataset above.'),
]
for r_i, row in enumerate(rows, start=1):
    for c_i, val in enumerate(row, start=1):
        cell = ws6.cell(row=r_i, column=c_i, value=val)
        cell.alignment = Alignment(wrap_text=True, vertical='top')
        if r_i == 1:
            cell.font = HEAD
            cell.fill = HEAD_FILL
ws6.column_dimensions['A'].width = 22
ws6.column_dimensions['B'].width = 55
ws6.column_dimensions['C'].width = 80
for r_i in range(2, len(rows) + 1):
    ws6.row_dimensions[r_i].height = 45

wb.save('SalesAnalysis_AnswerGraph_Logic.xlsx')
print('wrote SalesAnalysis_AnswerGraph_Logic.xlsx')
print('accounts exported:', len(accts_sorted))
